# 本文件定义了代理的状态结构，用于在交易代理系统中跟踪不同阶段的信息。

from typing import Annotated, Sequence
from datetime import date, timedelta, datetime
from typing_extensions import TypedDict, Optional
from tradingagents.agents import *
from langgraph.prebuilt import ToolNode
from langgraph.graph import END, StateGraph, START, MessagesState


# 研究员团队状态
class InvestDebateState(TypedDict):
    # 看涨对话历史
    bull_history: Annotated[str, "Bullish Conversation history"]
    # 看跌对话历史
    bear_history: Annotated[str, "Bearish Conversation history"]
    # 对话历史
    history: Annotated[str, "Conversation history"]
    # 最新回应
    current_response: Annotated[str, "Latest response"]
    # 最终评判决定
    judge_decision: Annotated[str, "Final judge decision"]
    # 当前对话的长度
    count: Annotated[int, "Length of the current conversation"]


# 风险管理团队状态
class RiskDebateState(TypedDict):
    # 激进代理的对话历史
    risky_history: Annotated[str, "Risky Agent's Conversation history"]
    # 稳健代理的对话历史
    safe_history: Annotated[str, "Safe Agent's Conversation history"]
    # 中立代理的对话历史
    neutral_history: Annotated[str, "Neutral Agent's Conversation history"]
    # 对话历史
    history: Annotated[str, "Conversation history"]
    # 最后发言的分析师
    latest_speaker: Annotated[str, "Analyst that spoke last"]
    # 激进分析师的最新回应
    current_risky_response: Annotated[str, "Latest response by the risky analyst"]
    # 稳健分析师的最新回应
    current_safe_response: Annotated[str, "Latest response by the safe analyst"]
    # 中立分析师的最新回应
    current_neutral_response: Annotated[str, "Latest response by the neutral analyst"]
    # 评判员的决定
    judge_decision: Annotated[str, "Judge's decision"]
    # 当前对话的长度
    count: Annotated[int, "Length of the current conversation"]


# 代理状态
class AgentState(MessagesState):
    # 我们感兴趣的交易公司
    company_of_interest: Annotated[str, "Company that we are interested in trading"]
    # 我们正在交易的日期
    trade_date: Annotated[str, "What date we are trading at"]

    # 发送此消息的代理
    sender: Annotated[str, "Agent that sent this message"]

    # 研究步骤
    # 来自市场分析师的报告
    market_report: Annotated[str, "Report from the Market Analyst"]
    # 来自社交媒体分析师的报告
    sentiment_report: Annotated[str, "Report from the Social Media Analyst"]
    # 来自新闻研究员的当前世界事务报告
    news_report: Annotated[
        str, "Report from the News Researcher of current world affairs"
    ]
    # 来自基本面研究员的报告
    fundamentals_report: Annotated[str, "Report from the Fundamentals Researcher"]

    # 研究员团队讨论步骤
    # 当前是否投资的辩论状态
    investment_debate_state: Annotated[
        InvestDebateState, "Current state of the debate on if to invest or not"
    ]
    # 分析师生成的计划
    investment_plan: Annotated[str, "Plan generated by the Analyst"]

    # 交易员生成的计划
    trader_investment_plan: Annotated[str, "Plan generated by the Trader"]

    # 风险管理团队讨论步骤
    # 评估风险的辩论当前状态
    risk_debate_state: Annotated[
        RiskDebateState, "Current state of the debate on evaluating risk"
    ]
    # 风险分析师做出的最终决定
    final_trade_decision: Annotated[str, "Final decision made by the Risk Analysts"]
